Repository BlueChilli/ChilliSource.Mobile.Logging, pull requests merged in 2018-02, with the labels that each got.

#16 Added Diagnostics Sink
  src/ChilliSource.Mobile.Logging/LoggerConfigurationExtensions.cs
  src/ChilliSource.Mobile.Logging/Sinks/DiagnosticsSink.cs
Labels: enhancement

#17 update to .netstandard 2.0
  build/build.cake
  src/ChilliSource.Mobile.Logging/ChilliSource.Mobile.Logging.csproj
Labels: enhancement

#18 upgrade core to 2.0.0
  src/ChilliSource.Mobile.Logging/ChilliSource.Mobile.Logging.csproj
Labels: build, enhancement

#19 2.0.0
  .gitignore
  build/build.cake
  build/tools/packages.config
  src/ChilliSource.Mobile.Logging/ChilliSource.Mobile.Logging.csproj
  src/ChilliSource.Mobile.Logging/ChilliSource.Mobile.Logging.sln
  src/ChilliSource.Mobile.Logging/LoggerConfigurationExtensions.cs
  src/ChilliSource.Mobile.Logging/Sinks/DiagnosticsSink.cs
  src/Directory.build.props
Labels: build, enhancement

#20 update version
  GitVersion.yml
Labels: bug
